version: '3.3'

services:
  plantuml-server:
    build:
      context: .
      dockerfile: Dockerfile.jetty
    image: plantuml/plantuml-server:jetty-local
    container_name: plantuml-server
    ports:
      - "127.0.0.1:9918:8080"
